[package]
name = "my-new-shell"
version = "0.1.0"
authors = ["Abhishek Bhardwaj <abshkbh@gmail.com>"]
edition = "2018"

[dependencies]
nix = "0.13.0"
libc = "0.2"
env_logger = "0.6.1"
log = "0.4.6"
log4rs = "0.8.3"
